score = 0;
const library = new Map();
library.set('слово','word');
library.set('спорт','sport');
library.set('мозг','brain');
library.set('благополучие','welfare');
library.set('трамвай','tram');
library.set('пара','pair');
library.set('книга','book');
library.set('видеть','see');
library.set('приходить','come');
library.set('идти','go');
library.set('счастливый','happy');
library.set('читать','read');
library.set('летать','fly');
library.set('нога','leg');
library.set('губа','lip');
library.set('нравиться','like');
library.set('мать','mother');
library.set('имя','name');
library.set('интернет','internet');
library.set('квадрат','square');
library.set('солнце','sun');
library.set('кровать','bed');
library.set('пить','drink');
library.set('есть','eat');
library.set('семья','family');
library.set('отец','father');

const stack = new Map(library);
